initial creation of samba container image
ArkCase/ark_samba pull request #1
Opened 2021-07-29 17:50 UTC by JonHolman

2021-07-29 20:10 UTC, fabricetriboix requested changes

2021-07-29 20:10 UTC, fabricetriboix commented on get-artifacts.sh
> +echo "Downloading samba nettle gnutls tar package"
In my own `get-artifacts.sh`, I left a comment saying from where I downloaded the artifact. This is for my future self as I am 100% certain that in 3 months time I won't be able to remember from where I downloaded it. I suggest you do something similar here, especially if John Shinnick built it for you.

2021-07-29 20:10 UTC, fabricetriboix commented on start.sh
> +echo "# Global parameters
Please use a here document, it's more readable. Example:

```
cat > /app/samba/etc/smb.conf <<EOF
[global]
  log level = 2
  ...etc...
EOF
```

2021-07-29 20:10 UTC, fabricetriboix commented on start.sh
> +--domain=ARKCASEDEMO \
I know very little about Samba, but to me it seems this "realm" and "domain" should be variables (i.e. environment variables passed by the orchestration layer, be it docker-compose or Kubernetes)... Is that correct?

2021-07-29 20:10 UTC, fabricetriboix commented on start.sh
> +\cp -pf /app/samba/private/krb5.conf /etc/krb5.conf
Is this file created by the previous samba-tool command? Or is it just some kind of static file? If it static, maybe you could do the copy in the Dockerfile rather than the startup file?

2021-07-29 20:10 UTC, fabricetriboix commented on start.sh
> +/app/samba/sbin/samba
Why do you need to start Samba before running some additional samba-tool commands?

2021-07-29 20:10 UTC, fabricetriboix commented on start.sh
> +tail -f /dev/null
Ideally, we want the last line of the startup script to be something like

```
exec /app/samba/sbin/samba
```

If we start Samba from this startup script and run it as a daemon, it won't receive the SIGTERM signal when Docker wants to shutdown the container.

2021-07-29 20:43 UTC, JonHolman commented on Dockerfile
> +RUN yum update --assumeyes
Updated.

2021-07-29 20:43 UTC, JonHolman commented on docker-compose.yaml
> +        privileged: true
Done.

2021-07-29 20:44 UTC, JonHolman commented on get-artifacts.sh
> +echo "Downloading samba nettle gnutls tar package"
I need to work with @jdshinnick to document the process of creating the artifact.

2021-07-29 20:44 UTC, JonHolman commented on start.sh
> +echo "# Global parameters
Updated.

2021-07-29 20:44 UTC, JonHolman commented on start.sh
> +--domain=ARKCASEDEMO \
That makes sense.  Can you give me an example of how I would do that?

2021-07-29 20:45 UTC, JonHolman commented on start.sh
> +\cp -pf /app/samba/private/krb5.conf /etc/krb5.conf
It's created by the previous samba-tool command.

2021-07-29 20:45 UTC, JonHolman commented on start.sh
> +/app/samba/sbin/samba
because samba needs to be running to accept those commands :(

2021-07-29 20:45 UTC, JonHolman commented on start.sh
> +tail -f /dev/null
I agree, I wish I could do that.

2021-07-30 10:15 UTC, fabricetriboix requested changes

2021-07-30 10:15 UTC, fabricetriboix commented on get-artifacts.sh
> +echo "Downloading samba nettle gnutls tar package"
All right, that's fine. I will mark this conversation as resolved for now. I trust you will check with John Shinnick and document this process.

2021-07-30 10:15 UTC, fabricetriboix commented on start.sh
> +--domain=ARKCASEDEMO \
@JonHolman You would "feed" environment variables to the Docker container. For example in the docker-compose file, you could have something like that:

```
version: "3"
  
services:
    samba:
        build: .
        image: ark_samba:latest
        environment:
          - SAMBA_REALM: ARKCASEDEMO.NET
          - SAMBA_DOMAIN: ARKCASEDEMO
...etc...
```

These environment variables will be defined when the startup script runs. So you would just need to do this in the startup script:

```
...snip...
# Create domain
/app/samba/bin/samba-tool domain provision \
--realm="$SAMBA_REALM" \
--domain="$SAMBA_DOMAIN" \
...snip...
```

That should just work. If it doesn't, please let me know.

Later, when using Helm charts, these environment variables can be part of a deployment file, and the variables can be set/modified in the `values.yaml` file situated at the top-level of the Helm chart. When you start working on the Helm chart, just let me know if this is confusing and I will guide you.

2021-07-30 10:15 UTC, fabricetriboix commented on start.sh
> +\cp -pf /app/samba/private/krb5.conf /etc/krb5.conf
All right, no worries! Could you please add a comment telling just that? Thanks!

2021-07-30 10:15 UTC, fabricetriboix commented on start.sh
> +/app/samba/sbin/samba
All right, I see. Could you please add a comment saying just that?

2021-07-30 10:15 UTC, fabricetriboix commented on start.sh
> +tail -f /dev/null
OK...

Maybe a workaround would be to do this:
  1. Start Samba
  2. Run the samba-tool commands
  3. Stop Samba
  4. The last line of the startup script can now be `exec /app/samba/sbin/samba`

Could you please try this workaround and see if that works? Thanks

2021-07-30 14:33 UTC, JonHolman commented on start.sh
> +SAMBA_ADMIN_PASSWORD='TempP@$$w0rd'
@fabricetriboix  should I change this to:
`if [[ -z "${SAMBA_ADMIN_PASSWORD}" ]]; then
  SAMBA_ADMIN_PASSWORD='TempP@$$w0rd'
fi
`
so that if helm sets the environment variable that will be used?

2021-07-30 15:23 UTC, fabricetriboix commented on start.sh
> +SAMBA_ADMIN_PASSWORD='TempP@$$w0rd'
@JonHolman  The idea is good, but the code won't work. If the `SAMBA_ADMIN_PASSWORD` variable is not set, trying to expand it will fail because of the `set -u` at the beginning of the script, if it you want to test that this variable is empty.

The following code will work when the `SAMBA_ADMIN_PASSWORD` variable is not set:

```
if [ ! -v SAMBA_ADMIN_PASSWORD ]; then
...
fi
```

Note that I am not expanding `SAMBA_ADMIN_PASSWORD` in the test.

All that being said, if it was for me I would just assume an important environment variable like `SAMBA_ADMIN_PASSWORD` is set, and I would happily let the container fails if it is not.

2021-07-30 20:02 UTC, JonHolman commented on start.sh
> +--domain=ARKCASEDEMO \
Thanks @fabricetriboix  this has been updated.

2021-07-30 20:02 UTC, JonHolman commented on start.sh
> +/app/samba/sbin/samba
Done.

2021-07-30 20:02 UTC, JonHolman commented on start.sh
> +tail -f /dev/null
Done, thanks @fabricetriboix

2021-07-30 20:03 UTC, JonHolman commented on start.sh
> +SAMBA_ADMIN_PASSWORD='TempP@$$w0rd'
Added `SAMBA_ADMIN_PASSWORD` in docker-compose with the environment variables that will be provided from there and later from helm.

2021-08-02 12:50 UTC, fabricetriboix commented on start.sh
> +while kill -9 `cat /app/samba/var/run/samba.pid`; do
@JonHolman `kill -9` is very brutal. Are you sure Samba will have time to write down whatever it has in memory to the filesystem before terminating? Would there be a softer way to stop Samba?

2021-08-02 21:37 UTC, JonHolman commented on start.sh
> +while kill -9 `cat /app/samba/var/run/samba.pid`; do
Thanks @fabricetriboix  this has been updated.

2021-08-03 09:23 UTC, fabricetriboix approved these changes

2021-08-03 10:12 UTC, naveen-armedia approved these changes

2021-08-04 13:34 UTC, merged